load("C:/Users/Valerie/Downloads/STAT 360/mars_project/STAT_360_mars_Project/mars/tests/testthat/testLOF.RData")
load("C:/Users/Valerie/Downloads/STAT 360/mars_project/STAT_360_mars_Project/mars/tests/testthat/testmc.RData")
data = data.frame(y=testfwd$y,testfwd$B)
lof = LOF(y~.-1, data, testmc)
all.equal(lof, testLOF)
